### ISSUE TITLE
SamplerCustomAdvanced: forward_orig_ipa() takes from 7 to 9 positional arguments but 10 were given

### ISSUE THREAD

**Issue by purzbeats** [Shakker-Labs/ComfyUI-IPAdapter-Flux#3]
![image](https://github.com/user-attachments/assets/696d2410-4f31-4b64-823e-c3dc1b641ac3)

```
!!! Exception during processing !!! forward_orig_ipa() takes from 7 to 9 positional arguments but 10 were given
Traceback (most recent call last):
  File "C:\ai\comfy\Comfy1\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ai\comfy\Comfy1\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ai\comfy\Comfy1\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ai\comfy\Comfy1\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ai\comfy\Comfy1\comfy_extras\nodes_custom_sampler.py", line 633, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "C:\ai\comfy\Comfy1\comfy\samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "C:\ai\comfy\Comfy1\comfy\samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\ai\comfy\Comfy1\comfy\samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\ai\comfy\Comfy1\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\ai\comfy\Comfy1\comfy\k_diffusion\sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\ai\comfy\Comfy1\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "C:\ai\comfy\Comfy1\comfy\samplers.py", line 706, in __call__
    return self.predict_noise(*args, **kwargs)
  File "C:\ai\comfy\Comfy1\comfy\samplers.py", line 709, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "C:\ai\comfy\Comfy1\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "C:\ai\comfy\Comfy1\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\ai\comfy\Comfy1\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 69, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "C:\ai\comfy\Comfy1\comfy\model_base.py", line 144, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\ai\comfy\Comfy1\.venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ai\comfy\Comfy1\.venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ai\comfy\Comfy1\comfy\ldm\flux\model.py", line 184, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options)
TypeError: forward_orig_ipa() takes from 7 to 9 positional arguments but 10 were given
```

**Comment by Rizzlord** [comment]
same here, i think we both are the best for feedback atm haha

**Comment by slmonker** [comment]
same!Wat r u doing shakker?

**Comment by purzbeats** [comment]
They're squashing these bugs fast as hell, let them cook! 👩‍🍳

**Comment by slmonker** [comment]
> Works now!

Thanks god!

**Comment by philipy1219** [comment]
The issue will occur in ComfyUI versions after commit 8ebf2d8 (Nov 12, 2024). The problem has been fixed in this commit: [4f1dcbbd312e1fc4ce6b3d2a4f1cf6e5fdaf27b1](https://github.com/Shakker-Labs/ComfyUI-IPAdapter-Flux/commit/4f1dcbbd312e1fc4ce6b3d2a4f1cf6e5fdaf27b1).
