### ISSUE TITLE
'DoubleStreamBlock' object has no attribute 'flipped_img_txt'

### ISSUE THREAD

**Issue by kzbuser** [Shakker-Labs/ComfyUI-IPAdapter-Flux#57]
'DoubleStreamBlock' object has no attribute 'flipped_img_txt'这个报错怎么解决

**Comment by kzbuser** [comment]
![Snipaste_2024-12-19_00-39-54](https://github.com/user-attachments/assets/3ff3a49d-823c-47aa-8409-3bd0dbc87e48)
![Snipaste_2024-12-19_00-39-17](https://github.com/user-attachments/assets/73336da7-e572-44d7-9309-2751d4d38e24)

**Comment by karthikg-09** [comment]
getting the same error after updating comfy

**Comment by capruokz** [comment]
me too how to fix its?

**Comment by philipy1219** [comment]
update comfy commit after [bda1482](https://github.com/comfyanonymous/ComfyUI/commit/bda1482a272e36315d39ef84663073f88d0a0367)

**Comment by seeyoo0898** [comment]
I'm having the same problem,How can I solve this problem?

**Comment by philipy1219** [comment]
> I'm having the same problem,How can I solve this problem?

Did you update comfy commit after [bda1482]?(https://github.com/comfyanonymous/ComfyUI/commit/bda1482a272e36315d39ef84663073f88d0a0367)

**Comment by w3988279** [comment]
同样问题 ，求解决

**Comment by w3988279** [comment]
以解决 更新ComfyUI 主题新版本即可

**Comment by Kallamamran** [comment]
Just tried it fully updated and have the same problem :(

```
2025-01-15T13:28:38.711800 - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IPAdapter-Flux\ipadapter_flux.py", line 157, in apply_ipadapter_flux
    FluxUpdateModules(bi, ip_attn_procs, image_prompt_embeds, is_patched)
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IPAdapter-Flux\utils.py", line 20, in FluxUpdateModules
    new_layer = DoubleStreamBlockIPA(original, procs, embs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IPAdapter-Flux\flux\layers.py", line 31, in __init__
    self.flipped_img_txt = original_block.flipped_img_txt
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'DoubleStreamBlock' object has no attribute 'flipped_img_txt'
```

**Comment by pizurny** [comment]
open layers.py anf change line 31 to this:
`self.flipped_img_txt = getattr(original_block, 'flipped_img_txt', False)`

**Comment by hnbbbc** [comment]
where is location layers.py?

python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'DoubleStreamBlock' object has no attribute 'flipped_img_txt'

Ours makes mistakes in this area.

**Comment by pizurny** [comment]
> where is location layers.py?
> 
> python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1931, in **getattr** raise AttributeError( AttributeError: 'DoubleStreamBlock' object has no attribute 'flipped_img_txt'
> 
> Ours makes mistakes in this area.

here: `ComfyUI-IPAdapter-Flux/flux/layers.py`

**Comment by Hermit6202** [comment]
> 以解决 更新ComfyUI 主题新版本即可

I'm now on Commit c55fd74 from ComfyUI 0.3.71 (21.11.2025) and still having the same error

**Comment by Hermit6202** [comment]
> open layers.py anf change line 31 to this: `self.flipped_img_txt = getattr(original_block, 'flipped_img_txt', False)`

Thanks, worked
